spring.application.name=demo

# JWT — configuration
app.jwt.issuer=high-card
app.jwt.audience=high-card-api
app.jwt.expiration-minutes=60
app.jwt.public-key-location=classpath:keys/public.pem
app.jwt.private-key-location=classpath:keys/private.pem